Add: PGBouncer Sample App
grafana/integration-sample-apps pull request #12
Opened 2024-02-13 05:04 UTC by BominRahmani

This PR adds the PGBouncer sample app. This sample app uses Jinja + Multipass to get a Postgres, PGBouncer, PGBouncer exporter, and Grafana agent setup.

2024-02-13 15:16 UTC, JonathanWamsley requested changes
First pass, PgBouncer is active but the exporter and Grafana agent is not when I tested it

2024-02-13 15:16 UTC, JonathanWamsley commented on pgbouncer/Makefile
> +	@multipass exec $(VM_NAME) -- curl http://localhost:9127/metrics > prometheus_metrics
Got a `curl: (7) Failed to connect to localhost port 9127 after 3 ms: Connection refused` when trying to fetch prometheus metrics.

2024-02-13 15:16 UTC, JonathanWamsley commented on pgbouncer/README.md
> +- `make load-test`: Generates load on the Solr cluster for testing purposes.
Does not exist

2024-02-13 15:16 UTC, JonathanWamsley commented on pgbouncer/README.md
> +- `solr_cluster_name`: Name of the Solr cluster.
remove/update default parameters as necessary

2024-02-13 15:16 UTC, JonathanWamsley commented on pgbouncer/README.md
> +When deploying the Apache Solr and ZooKeeper Cluster Sample App, you may encounter issues that require debugging. Here are some tips to validate the setup and troubleshoot common problems.
Needs to be updated from Solr debugging

2024-02-13 15:16 UTC, JonathanWamsley commented on pgbouncer/README.md
> +multipass shell apache-solr-zookeeper-instance-1
Needs to point to your sample app

2024-02-13 15:16 UTC, JonathanWamsley commented on pgbouncer/README.md
> +## Validating Services
I went in the shell and don't know which services are not working. The PgBouncer does seem to be active when running `sudo systemctl status pgbouncer` I am not sure about the exporter. I am unable to get metrics back.

2024-02-13 15:16 UTC, JonathanWamsley commented on pgbouncer/README.md
> +  systemctl status grafana-agent
The sample app did not install the grafana-agent on my end either
![Screenshot 2024-02-13 at 10 11 24 AM](https://github.com/grafana/integration-sample-apps/assets/13648435/a8f3d6c4-bb57-4404-9a38-dea7256d456c)

2024-02-13 15:16 UTC, JonathanWamsley commented on pgbouncer/Makefile
> +VM_NAME := pgbouncer-sampleapp
Since the repo name uses `integration-sample-apps`, can you make it `pgbouncer-sample-app` and update name usage to follow the flow

2024-02-13 15:16 UTC, JonathanWamsley commented on pgbouncer/README.md
> +   cd integration-sample-apps/apache-solr
update to pgbouncer

2024-02-14 17:13 UTC, JonathanWamsley approved these changes
✅ LGTM

2024-02-16 18:38 UTC, mshahzeb approved these changes
LGTM!

Small comment on the Readme

2024-02-16 18:38 UTC, mshahzeb commented on pgbouncer/README.md
> +# PgBouncer Sample App
Would be best to mention which platforms are supported (Linux, Windows, x86, arm64) and specifically for which platform is this Readme for

2024-02-23 17:24 UTC, merged