OpenStack Sample App
grafana/integration-sample-apps pull request #13
Opened 2024-02-22 19:47 UTC by Caleb-Hurshman

Adds a Terraform script to launch a GCP instance with OpenStack (devstack), the `openstack-exporter`, and the Grafana agent installed.

2024-02-26 20:54 UTC, BominRahmani commented on openstack/terraform.tfstate.backup
> +{
You don't want this file commited.

2024-02-26 20:54 UTC, BominRahmani commented on openstack/terraform.tfstate
> +{
You do not want this file commited.

2024-02-26 20:57 UTC, BominRahmani requested changes
Couple of things, Also can you run a `terraform fmt`. Im not sure if it matters, but i also notice a lot of the files do not have an extra line at the end.

2024-02-26 20:59 UTC, BominRahmani commented on openstack/variables.tfvars
> +gcp_auth_file="<Path/to/your/gcp/service-account/credentials>"
Is there a reason this one doesn't highlight the `gcp_auth_file` in blue? It looks like the variable declaration of all variables following are highlighted in blue.

2024-02-27 13:59 UTC, BominRahmani approved these changes
LGTM!

2024-03-06 13:56 UTC, Caleb-Hurshman commented
@Dasomeone On the subject of Multipass, I was initially attempting to build this sample to run with Multipass but ran into issues with executing on an M2 Mac. Essentially the `nova` service that gets installed by devstack is somewhat supported, but not officially supported, making setup on a Multipass VM impossible for me to test on my machine.

2024-03-06 14:44 UTC, Dasomeone commented
> @Dasomeone On the subject of Multipass, I was initially attempting to build this sample to run with Multipass but ran into issues with executing on an M2 Mac. Essentially the `nova` service that gets installed by devstack is somewhat supported, but not officially supported, making setup on a Multipass VM impossible for me to test on my machine.

That's a very fair point then! Might be worth adding a small known issues/platform support/etc section to the readme just to explain that, in case we attempt to convert it in the future

2024-03-06 16:54 UTC, Caleb-Hurshman commented on openstack/loadgen.tf
> +  sleep $SLEEP_DURATION
@Dasomeone This aspect of the loadgen script was to generate variance in the dashboard panels. Without these two functions, all the timeseries would be flat lines, so this pattern of creating and deleting resources creates a more visually interesting result when the user looks at the mixin. If that's not a priority then I'm happy to modify the script.

2024-03-11 11:57 UTC, Dasomeone commented on openstack/loadgen.tf
> +  sleep $SLEEP_DURATION
Hmm that does make sense, but maybe we could reduce it to a shorter interval like 2-2.5 minutes? Either way I'm nitpicking here and it's good enough as-is.

2024-03-11 11:58 UTC, Dasomeone commented on openstack/main.tf
> +}
Newline

2024-03-11 11:58 UTC, Dasomeone commented on openstack/ubuntu-versions.tf
> +}
newline

2024-03-11 11:59 UTC, Dasomeone commented on openstack/provider-variables.tf
> +}
newline

2024-03-11 11:59 UTC, Dasomeone commented on openstack/provider-main.tf
> +}
newline

2024-03-11 11:59 UTC, Dasomeone commented on openstack/network-variables.tf
> +}
newline

2024-03-11 11:59 UTC, Dasomeone commented on openstack/network-main.tf
> +}
newline

2024-03-11 11:59 UTC, Dasomeone commented on openstack/network-firewall.tf
> +}
newline

2024-03-11 13:05 UTC, Dasomeone approved these changes
LGTM, but we need a second approval from @rgeyer

2024-03-11 21:43 UTC, rgeyer commented on openstack/bootstrap-vm.tp1
> +cat <<'CONFIG' | sudo tee /etc/grafana-agent.yaml
Yes, and a lot of the "boilerplate" for cloud-init scripts, such as installing and configuring the agent should be shared snippets as well.

I think that this repo will eventually have a top-level library of these sorts of things which can be brought it as part of the automation.

2024-03-11 21:45 UTC, rgeyer commented
> > @Dasomeone On the subject of Multipass, I was initially attempting to build this sample to run with Multipass but ran into issues with executing on an M2 Mac. Essentially the `nova` service that gets installed by devstack is somewhat supported, but not officially supported, making setup on a Multipass VM impossible for me to test on my machine.
> 
> That's a very fair point then! Might be worth adding a small known issues/platform support/etc section to the readme just to explain that, in case we attempt to convert it in the future

We may have to re-evaluate our use of multipass for this reason, or track the M2 Mac support more closely.

This was true for the "minikube" version of the multipass VM as well. Seems apple silicon support is taking it's sweet time in many ecosystems.

2024-03-11 21:48 UTC, rgeyer approved these changes
LGTM, sorry for gatekeeping this so long!

2024-03-12 12:33 UTC, merged